language: go
sudo: required
services:
- docker
go:
- 1.10.x
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
  - glide install
  - env GOOS=linux GOARCH=arm go build -o bin/server ./server

cache:
  directories:
  - vendor
#env:
#  global:
#    - COMMIT=${TRAVIS_COMMIT::8}
#    - secure: ds93G5aW/jaVOMuN3sq+Tp/BHvTdZ6lWMai0GZXRnAYYAyKfJnbIRSO9BvCd7Ve2sGvrzCd9JPMtvULcY1YU/dXeut+6t/r54YEzOMj2OjHMffk3tmKAUjDIkvTVtuIOkSdRZdTjul7/khxqDOvZ9W2JbCWlq2ODhV+u8sRcvUEnNavO4t+mmORMXboHOva2RTozTFkfLJaDhC6ufXG4SwQP8v8mpSedeXUudU1R1aOnx0kizVORgHdLup0EGyXwALpSdu98caiBxPlq41+yi7HTFdrwi8y6vJyVwq8gippr4ZXscovGQzisGW1RFS/vgNQDGqZD/KEd4S+RFRNCB4NTMN4KjY25vF60XDD83neZWEfBx6OBydHvr5XxBmelik/20+nvY+z7CyIsU5CItD7Ek4gEHZ9/ZbNLtb18VmLH46je2j3xbq59zajGfcUA1PZk4JLAHaGmEGkzKTr5S9sC6Jg0CVLjtZ9NOyS6C99pzMT8zZlFfP3WdWH+w6R4v4IklF+e2nQxisy/c2iKLFyq6LqqGSjehIFNfW9T46uzu2WjE8TjkwlK8ERQacNWBaZLVJQ+0s0ua9BeiT1i82CIPDdksh9U135xiLHbE6gIU/x1uG0/CyM2CYfqyw6l57NiKu7OMVYukkEp+HsxT3a+KNMF4VtG+WNdrGfdDlY=
#    - secure: AJG7o5r2sgSra9PqPVgEn71YTjnTivRIpXArVOZWBYoCGORBdt/Qc/Sc3VVMO/5AOXblzQ060JQtYxNIhyn7zG88dALafi9PMs/AFu11J4WBwmalBmocfLA8erTH3s+np98gomL0c3d0vblOjZd3bZM5jOyTHtcq+mE0Uq4/bajVWCivVVk+lE5av63Qslpfz5c1HOoVrJV5Mp8BmAyf7zrB7FIZPZN0iLIKAPplDN1Y+Bmt1FFWRan4r7HXicFGMuo7v9RiQH8Pb6R66HVzKP1wJpgOZwDsdTsTChT2iEcnTMuRRKvDPHpQtD0wy70qIzIya4HYVIkJrSWwszir9TV3vV67q1Hx2PVsCSYRumv0+GvwVgdkahN5TmnUll/d092/2jZGkK9oR5eic8hZamRCEyYqgv1ecNvI4DUjcOoJ9PROr9MMxa5j7h9z9Bow9vIx7Rx+GpbagVjWgOL8lG7s3H+2FDKMIBq/ZzhURsp6vBx59QOR9WRy+85FSvimldqoTETQst9EgsppxERb+UGLSEzc/j3xzjO0igax197DrwUW2303xJebDWze/hPBVZZDV3JLnngL2uEKV0J+GORXUjsSVSZPw7x0XKIXbUvTvsRXPUYgrjG7tut1K41PBEH3ZsRSYUVCXciq3gnmtlkPAjzBdaysePp8+bZB+ug=
#after_success:
#  - export version="v`date  +"%Y%m%d%H%M%s"`"
#  - export REPO=hub.xycloud.com/4164/web-crawler:${version}
#  - echo "REPO ===== $REPO"
#  - env
#  - docker build -f web-crawler-docker -t $REPO .
#  - docker login hub.xycloud.com -u $DOCKER_USER -p $DOCKER_PASS
#  - sleep 2 && docker push $REPO
