language: go
sudo: required
services:
- docker
go:
- 1.10.x
install:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- build-server.sh arm
- build-server.sh amd64
- build-client.sh arm
- build-client.sh amd64

cache:
  directories:
  - vendor
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
  - secure: cspvRo7ju/Qh28NAm1Bc63xHVbk0zd0AaigViU6SyAe7G27u/Dx8HN6CWmmrW1v6uTE595ZkwcQwTRzPMkL9S+1IDuDq7vcMVgF3jFT8n1YLQgNxJPYLVbKA4PFMl8Y2cvby20MAd1zwDnvLWyF5BmlNXDY167prgVOQDW6Ybk2YSC2x084J56X7+2QRdNdnuVxH6xnD9TLFWq/pvPz8OQq4/LPWI0fGbATmmDCRkcbChhXavVDhzdlXMT96M+YPv2ySTl69yJXgEhRN6csXe5+LZBOgEGDAr5pDomy0oJQpJwK6cwBDtYE9YeNL9V7hzcgWDcG7BoZ0vHh5OirquWqI7m2p2ckkvpgAadKcenGcCusQVSkFIX/HO13ZLzEquj+QG7sDeW7BgpdsMzVJSlyvw8cwqaWJVUkkhRjy151f6XUZB3b8+tM6YhGs48oHUVDHqNAdkFKpJxK5D1Y2dcRZEq75dKSbNkFpXtd5kmb2oIILQJoNfXcibOgdFviE95SDsPax4vwoG/r08HXt6QyVetu0iUbfRnssYRQ36Ar5Jo3RumaloLVv8ozyOSdcOjDTzzW8l9gd2NopwXE53UXgDbv9lQPKd+XUnHBtTZgKZGnyWGnNaWhM797L59Zx3QZOD+UWHphh3lSD4F1Y1RzMShxJMl8LdkVvXLPiqKU=
  - secure: E0WIntMVOctLQmIiqiFo4OMlBAwiyQZLxKdwoowfKuSaapfZVupbJzB2iERCKacuW+udqmNK6EW7mNG8GUzZwJv0yo2vihojLNOXn8XwE2y/5D7/P2quI0sG8u1qG0h+cNHmI2FFJ5vnXAybHOmVcsTLZxl0rV4+YHgxAgIo8FT/tWSSUm2nYNA1G7Ggtz/fS2aXm8Z0WJs2J8s08kMxmuJQMdVFpIgFfa9Oh2vhAjyfV0xMfI1IdkMcH2CrVVT2bOoWLjw6HDZXdISdVx1VjzZWHvzqq/KdRMOCyrt2Wn3pDXDr7bFR0iv1GVJeNQRbmDYnhO32KiQdMaqmd4sUeIjdDNnBNViQlGoxv6l8cG998GkB8UdTU1L8g7UHXleV4HRVdEIQ8bymylHJm5XS9Cg6HAEXf+pyUgZZfFqh5ZwSo3a1/Qmz1V2fq+dyuJny5RxzPK0vb89QfhJ0bRQ7KxZkCjbaPi7cXKj5/sKrK5j+zk7Cbtr3Zp16WPIc3nJD57Yw4WPATXliUY/Gv5eFrM++d9UT1LZlAXDW+hZYat1XQT2gTRfqJeNewGkT7GhZnZE0e+Sos6lh1tOSKhyHyA7kemwpT3hjKq5586s4P6bMT40yQVuLsIVCd8b+qdYAvLQ97ASNxxmfm7HDNRzMWKLNtR0L5s1tcohSAYrMz5o=

