// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/action.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Actions int32

const (
	Actions_START Actions = 0
	Actions_PAUSE Actions = 1
	Actions_STOP  Actions = 2
)

var Actions_name = map[int32]string{
	0: "START",
	1: "PAUSE",
	2: "STOP",
}
var Actions_value = map[string]int32{
	"START": 0,
	"PAUSE": 1,
	"STOP":  2,
}

func (x Actions) String() string {
	return proto.EnumName(Actions_name, int32(x))
}
func (Actions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_action_7700ed396daf640f, []int{0}
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	RequestId            uint64   `protobuf:"varint,5,opt,name=requestId" json:"requestId,omitempty"`
	Body                 *any.Any `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_7700ed396daf640f, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Request) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Request) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Describe             string   `protobuf:"bytes,3,opt,name=describe" json:"describe,omitempty"`
	RequestId            uint64   `protobuf:"varint,5,opt,name=requestId" json:"requestId,omitempty"`
	Body                 *any.Any `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_7700ed396daf640f, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetDescribe() string {
	if m != nil {
		return m.Describe
	}
	return ""
}

func (m *Response) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Response) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterEnum("proto.Actions", Actions_name, Actions_value)
}

func init() { proto.RegisterFile("proto/action.proto", fileDescriptor_action_7700ed396daf640f) }

var fileDescriptor_action_7700ed396daf640f = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x85, 0xf1, 0x92, 0x90, 0x64, 0x68, 0xa2, 0x11, 0x85, 0x59, 0x51, 0x44, 0x5b, 0x19, 0x8a,
	0x44, 0x82, 0x13, 0xa4, 0xa0, 0xa0, 0x62, 0xe5, 0x84, 0x03, 0xe4, 0x67, 0x88, 0x56, 0x62, 0xed,
	0x10, 0x67, 0x0b, 0xdf, 0x85, 0xc3, 0xa2, 0x4c, 0xb4, 0xcb, 0x05, 0xa8, 0xfc, 0xbe, 0xf1, 0x3c,
	0x7d, 0x96, 0x01, 0xc7, 0xc9, 0xce, 0xb6, 0x68, 0xba, 0xf9, 0x60, 0x4d, 0xce, 0x80, 0x21, 0x1f,
	0xdb, 0xfb, 0xc1, 0xda, 0xe1, 0x8b, 0x0a, 0xa6, 0xf6, 0xf4, 0x59, 0x34, 0xc6, 0xaf, 0x1b, 0x3b,
	0x0f, 0x91, 0xa6, 0xef, 0x13, 0xb9, 0x19, 0x11, 0x02, 0xd3, 0x1c, 0x49, 0x8a, 0x4c, 0xa8, 0x44,
	0x73, 0x5e, 0x66, 0xb3, 0x1f, 0x49, 0x6e, 0x32, 0xa1, 0x42, 0xcd, 0x19, 0x1f, 0x20, 0x99, 0xd6,
	0xca, 0x5b, 0x2f, 0xc3, 0x4c, 0xa8, 0x40, 0xff, 0x0d, 0x50, 0x41, 0xd0, 0xda, 0xde, 0xcb, 0x20,
	0x13, 0xea, 0xf6, 0xf9, 0x2e, 0x5f, 0xd5, 0xf9, 0x59, 0x9d, 0x97, 0xc6, 0x6b, 0xde, 0xd8, 0xfd,
	0x08, 0x88, 0x35, 0xb9, 0xd1, 0x1a, 0xc7, 0xa2, 0xce, 0xf6, 0x17, 0xf9, 0x92, 0x51, 0x42, 0x74,
	0x24, 0xe7, 0x9a, 0x61, 0xf5, 0x27, 0xfa, 0x8c, 0xb8, 0x85, 0xb8, 0x27, 0xd7, 0x4d, 0x87, 0x96,
	0xe4, 0x35, 0x5f, 0x5d, 0xf8, 0xbf, 0x9e, 0xf7, 0xf4, 0x08, 0x51, 0xc9, 0x7f, 0xe9, 0x30, 0x81,
	0xb0, 0xaa, 0x4b, 0x5d, 0xa7, 0x57, 0x4b, 0xdc, 0x97, 0x1f, 0xd5, 0x6b, 0x2a, 0x30, 0x86, 0xa0,
	0xaa, 0xdf, 0xf7, 0xe9, 0xa6, 0xbd, 0xe1, 0xfa, 0xcb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1,
	0x64, 0x15, 0xa3, 0x83, 0x01, 0x00, 0x00,
}
