// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/action.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Actions int32

const (
	Actions_START Actions = 0
	Actions_PAUSE Actions = 1
	Actions_STOP  Actions = 2
)

var Actions_name = map[int32]string{
	0: "START",
	1: "PAUSE",
	2: "STOP",
}
var Actions_value = map[string]int32{
	"START": 0,
	"PAUSE": 1,
	"STOP":  2,
}

func (x Actions) String() string {
	return proto.EnumName(Actions_name, int32(x))
}
func (Actions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_action_45cf91886105d905, []int{0}
}

type Action struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Args                 *any.Any `protobuf:"bytes,4,opt,name=args" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_action_45cf91886105d905, []int{0}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Action) GetArgs() *any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Action)(nil), "proto.Action")
	proto.RegisterEnum("proto.Actions", Actions_name, Actions_value)
}

func init() { proto.RegisterFile("proto/action.proto", fileDescriptor_action_45cf91886105d905) }

var fileDescriptor_action_45cf91886105d905 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x73, 0x84, 0x58, 0xc1, 0x94, 0x94,
	0x64, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x98, 0x97, 0x54, 0x9a, 0xa6, 0x9f, 0x98, 0x57,
	0x09, 0x51, 0xa1, 0x14, 0xc5, 0xc5, 0xe6, 0x08, 0xd6, 0x21, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98,
	0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x83, 0xc4, 0x4a, 0x2a, 0x0b, 0x52,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x0d, 0x2e, 0x96, 0xc4, 0xa2, 0xf4,
	0x62, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x11, 0x3d, 0x88, 0xd9, 0x7a, 0x30, 0xb3, 0xf5,
	0x1c, 0xf3, 0x2a, 0x83, 0xc0, 0x2a, 0xb4, 0x34, 0xb9, 0xd8, 0x21, 0x66, 0x17, 0x0b, 0x71, 0x72,
	0xb1, 0x06, 0x87, 0x38, 0x06, 0x85, 0x08, 0x30, 0x80, 0x98, 0x01, 0x8e, 0xa1, 0xc1, 0xae, 0x02,
	0x8c, 0x42, 0x1c, 0x5c, 0x2c, 0xc1, 0x21, 0xfe, 0x01, 0x02, 0x4c, 0x49, 0x6c, 0x60, 0xed, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x2e, 0xdf, 0x7f, 0xc5, 0x00, 0x00, 0x00,
}
